### ISSUE TITLE
keyword half_init in class InputRegion initializer

### ISSUE THREAD

**Issue by tvieijra** [jemisjoky/TorchMPS#1]
When constructing an MPS as in the example code, I get a TypeError at line 25 of torchmps.py:

`TypeError: __init__() got an unexpected keyword argument 'half_init'`

When looking in the code, the initializer of InputRegion indeed does not appear to specify a keyword half_init:

```
    def __init__(self, tensor=None, input_dim=None, bond_dim=None,
                 feature_dim=None, init_std=1e-9, min_init=False):
        super().__init__()
        # Register our tensor as a Pytorch Parameter
        self.tensor = nn.Parameter(tensor.contiguous())
```

I tried to change the keyword to min_init, which solved the problem, but an 

`AttributeError: 'NoneType' object has no attribute 'contiguous'`

was raised when executing line 590 of torchmps.py:

`self.tensor = nn.Parameter(tensor.contiguous())`

I get the same errors when executing the example script.

**Comment by jemisjoky** [comment]
Thanks for raising the issue @tvieijra! This arose from having refactoring my code, but then having only half of the updates included due to some funny git merging. The most recent commit should have that fixed, but let me know if you encounter any related issues!
