### ISSUE TITLE
Question about bond dimension

### ISSUE THREAD

**Issue by AdarshMJ** [jemisjoky/TorchMPS#5]
Hello! 
Excellent work @jemisjoky I had a rather silly question, Im still a newbie and Im trying to understand tensor networks. So the paper by Stoudenmire talks about the bond dimension as a tensor, but in the TorchMPS library we just set, say bond_dim = 20, which is an integer, am I missing something here? Shouldn't bond dimension be a tensor?

**Comment by jemisjoky** [comment]
Hi @AdarshMJ,

Really sorry for the slow reply! In [supervised learning with tensor networks](http://papers.nips.cc/paper/6211-supervised-learning-with-tensor-networks.pdf) (the one I think you're referring to), they also use bond dimension to refer to the same thing as in TorchMPS, the size of the vector space connecting two adjacent _A_ tensors in the MPS representation. But they also introduce an adaptive optimization scheme, and some of the tensors used as intermediaries there (the _B_ tensors) are referred to as "bond tensors". Maybe that is what you're thinking of?

Either way, let me know if you have any more questions and I'll try to get back to you faster the next time ;)
